version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - yum install -y amazon-efs-utils unzip git jq

  pre_build:
    commands:
      - echo "Mounting EFS..."
      - export EFS_ID=${efs_id}
      - mkdir -p /mnt/efs
      - mount -t efs -o tls $EFS_ID:/ /mnt/efs

  build:
    commands:
      - echo "Copying updated Node.js code into EFS..."
      - mkdir -p /mnt/efs/code
      - cp -r Nodejs/index.js Nodejs/package.json /mnt/efs/code/

  post_build:
    commands:
      - echo "Restarting PM2 app on EC2s..."
      - |
        aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --comment "Restart Node.js app" \
          --instance-ids ${instance_ids} \
          --parameters 'commands=["pm2 restart all"]' \
          --region us-east-2

      - echo "Installing and configuring NGINX on EC2s..."
      - |
        aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --comment "Install and configure NGINX" \
          --instance-ids ${instance_ids} \
          --parameters 'commands=[
            "sudo yum install -y nginx",
            "sudo systemctl enable nginx",
            "sudo systemctl start nginx",
            "sudo bash -c \\\"cat > /etc/nginx/conf.d/nodeapp.conf <<'CONFIG'\nserver {\n  listen 80;\n  server_name _;\n  location / {\n    proxy_pass http://localhost:3000;\n    proxy_http_version 1.1;\n    proxy_set_header Upgrade \$http_upgrade;\n    proxy_set_header Connection 'upgrade';\n    proxy_set_header Host \$host;\n    proxy_cache_bypass \$http_upgrade;\n  }\n}\nCONFIG\\\"",
            "sudo rm -f /etc/nginx/conf.d/default.conf",
            "sudo nginx -t && sudo systemctl reload nginx"
          ]' \
          --region us-east-2
