name: Explicit Terraform Module Deployment

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: us-east-2
  TF_STATE_BUCKET: vj-test-benvolate
  MODULE: Network                               # Network EFS EC2 Load Balancer

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Run deploy.sh for ${{ env.MODULE }}
        run: |
          echo "🚀 Deploying $MODULE"
          bash terraform/code/${{ env.MODULE }}/deploy.sh
